version: "3.8"
name: "taxi-app"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: taxi_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - taxi-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/taxi_app
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  taxi-data:
