spring:
  application:
    name: taxi-app
  datasource:
#    url: jdbc:postgresql://localhost:5432/taxi_app
#    username: postgres
#    password: Egor2004

    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
  security:
    user:
      name: admin
      password: admin

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
logging:
  level:
    org:
      springframework:
        security: DEBUG
